#%RAML 1.0 DataType
displayName: SDLC Metrics Datatype
description: Models the metrics extracted from SDLC systems
properties:
  date:
    type: datetime
  sdlcMetrics: 
    type: object
    properties:


      # System Specific
      bitBucketMetrics?: 
        properties:
          totalRepositories:
            type: integer  
      confluenceMetrics?: 
        type: object
        properties:
          totalPages:
            type: integer
          totalPagesCreatedInLast30Days:
            type: integer
          totalPagesUpdatedInLast30Days:
            type: integer
          topContributorsInLast30Days: 
            type: object        
      jenkinsMetrics?: 
        properties:
          totalJobs?:
            type: integer
          totalSuccessJobs?:
            type: integer 
          totalFailedJobs?:
            type: integer 
          totalUnexecutedJobs?:
            type: integer 
      jiraMetrics?: 
        properties:
          workItemsInBacklog:
            type: integer
          workItemsInSprint:
            type: integer  
          workItemsInSprintByType: 
            type: object
          workItemsInSprintByStatus:
            type: object
      splunkMetrics?: 
        properties:
          totalDashboards:
            type: integer
      azuredevopsBoardsMetrics?:
        properties: 
          workItemsInBacklog:
            type: integer
          workItemsInSprint:
            type: integer  
          workItemsInSprintByType: 
            type: object
          workItemsInSprintByStatus:
            type: object
      azureDevopsReposMetrics?:
        properties:
          totalRepositories:
            type: integer  
      azureDevopsPipelinesMetrics?:
        properties:
          totalJobs?:
            type: integer
          totalSuccessJobs?:
            type: integer 
          totalFailedJobs?:
            type: integer 
          totalUnexecutedJobs?:
            type: integer 
example: !include ../../examples/collectors/responses/get-sdlc-metrics.json
    
  
